_investStocks.ctx.register("AllUsaStocks")
    .asCtor(AllUsaStocks);

function AllUsaStocks(){
    this.getAll = getAll;

    let _stocks;
    let urlBase;

    function getAll(){
        return _stocks;
    }

    function ctor(){
        urlBase = "https://ru.investing.com/equities/";
        _stocks = [];

        add('Boeing', 'boeing-co', 'BA');
        add('General Motors', 'gen-motors', 'GM');
        add('Chevron', 'chevron', 'CVX');
        add('Citigroup', 'citigroup', 'C');
        add('Bank of America', 'bank-of-america', 'BAC');
        add('AT&T', 'at-t', 'T');
        add('Caterpillar', 'caterpillar', 'CAT');
        add('Intel', 'intel-corp', 'INTC');
        add('Microsoft', 'microsoft-corp', 'MSFT');
        add('Alcoa', 'alcoa', 'AA');
        add('Ford Motor', 'ford-motor-co', 'F');
        add('eBay', 'ebay-inc', 'EBAY');
        add('Dell', 'dell-inc', 'DVMT');
        add('Walt Disney', 'disney', 'DIS');
        add('Cisco', 'cisco-sys-inc', 'CSCO');
        add('Deere&Company', 'deere---co', 'DE');
        add('FedEx', 'fedex-corp', 'FDX');
        add('General Mills', 'general-mills', 'GIS');
        add('Corning', 'corning-inc', 'GLW');
        add('The Goodyear Tire&Rubber', 'goodyear-tire', 'GT');
        add('Goldman Sachs', 'goldman-sachs-group', 'GS');
        add('JPMorgan', 'jp-morgan-chase', 'JPM');
        add('Kimberly-Clark', 'kimberly-clark', 'KMB');
        add('Kraft Heinz', 'kraft-foods-inc', 'KHC');
        add('Coca-Cola', 'coca-cola-co', 'KO');
        add('McDonald’s', 'mcdonalds', 'MCD');
        add('Eli Lilly', 'eli-lilly-and-co', 'LLY');
        add('Oracle', 'oracle-corp', 'ORCL');
        add('Merck&Co', 'merck---co', 'MRK');
        add('Motorola', 'motorola-inc', 'MSI');
        add('3M', '3m-co', 'MMM');
        add('Office Depot', 'office-depot', 'ODP');
        add('Puma SE', 'puma-se-cfd?cid=6309', 'PMMAF');
        add('Gagfah', 'gagfah-sa', 'GGFHF');
        add('Vertex Pharma', 'vertex-pharm', 'VRTX');
        add('Monster Beverage 1990', 'monster-beverage', 'MNST');
        add('Teva ADR', 'teva-pharmaceutical-inds-ltd', 'TEVA');
        add('Fifth Third', 'fifth-third-bk', 'FITB');
        add('Sears Holdings', 'sears-hldgs-corp', 'SHLD');
        add('Cintas', 'cintas-corp', 'CTAS');
        add('Autodesk', 'autodesk-inc', 'ADSK');
        add('DISH Network', 'dish-network', 'DISH');
        add('Gilead', 'gilead-sciences-inc', 'GILD');
        add('Express Scripts', 'express-scripts-inc', 'ESRX');
        add('aTyr Pharma', 'life-tech-corp', 'LIFE');
        add('Alphabet A', 'google-inc', 'GOOGL');
        add('Fiserv', 'fiserv-inc', 'FISV');
        add('Liberty Global', 'liberty-global-inc', 'LBTYA');
        add('PDL BioPharma', 'pdl-biopharma-inc', 'PDLI');
        add('Adobe', 'adobe-sys-inc', 'ADBE');
        add('BlackBerry', 'research-in-motion-ltd', 'BB');
        add('Qualcomm', 'qualcomm-inc', 'QCOM');
        add('SINA Corp', 'sina-corp', 'SINA');
        add('Baidu', 'baidu.com', 'BIDU');
        add('Sohucom', 'sohu-com-inc', 'SOHU');
        add('Discovery', 'discovery-holding-co', 'DISCA');
        add('Sonus Networks', 'sonus-networks', 'SONS');
        add('Applied Materials', 'applied-matls-inc', 'AMAT');
        add('Steel Dynamics', 'steel-dynamics', 'STLD');
        add('Cadence Design', 'cadence-design-system-inc', 'CDNS');
        add('Bed Bath&Beyond', 'bed-bath---beyond-inc', 'BBBY');
        add('Microchip', 'microchip-technology-inc', 'MCHP');
        add('Wynn Resorts', 'wynn-resorts-ltd', 'WYNN');
        add('Intuitive Surgical', 'intuitive-surgical-inc', 'ISRG');
        add('Nasdaq Inc', 'nasdaq-omx-group', 'NDAQ');
        add('Ryanair ADR', 'ryanair-hldgs', 'RYAAY');
        add('Apollo Bancorp', 'apollo-group-inc', 'APLO');
        add('Infosys ADR', 'infosy-tech', 'INFY');
        add('Altaba', 'yahoo-inc', 'AABA');
        add('JetBlue', 'jet-blue', 'JBLU');
        add('Spartan Motors', 'spartan-motors', 'SPAR');
        add('Henry Schein', 'henry-schein', 'HSIC');
        add('Paychex', 'paychex-inc', 'PAYX');
        add('VeriSign', 'verisign-inc', 'VRSN');
        add('Apple', 'apple-computer-inc', 'AAPL');
        add('Fastenal', 'fastenal-co', 'FAST');
        add('Dentsply', 'dentsply-intl-inc-new', 'XRAY');
        add('Crocs', 'crocs', 'CROX');
        add('Zions', 'zions-bancorp', 'ZION');
        add('Northern Trust', 'northern-trust', 'NTRS');
        add('Citrix Systems', 'citrix-sys-inc', 'CTXS');
        add('Lamar', 'lamar-advertising-co', 'LAMR');
        add('Patterson-UTI Energy', 'patterson-uti-energy-inc', 'PTEN');
        add('Atlanticuss', 'atlanticuss', 'ATLC');
        add('CH Robinson', 'c-h-robinson-worldwide-inc', 'CHRW');
        add('Sirius XM Hld Inc', 'sirius-satellite-radio-inc', 'SIRI');
        add('Alpine Immune Sciences', 'novellus-sys', 'ALPN');
        add('PACCAR', 'paccar-inc', 'PCAR');
        add('Pan American Silver', 'pan-american-silver-corp', 'PAAS');
        add('Amazon.com', 'amazon-com-inc', 'AMZN');
        add('Ross Stores', 'ross-stores-inc', 'ROST');
        add('Viavi Solutions', 'jds-uniphase-corp', 'VIAV');
        add('NetEase', 'netease.com', 'NTES');
        add('NetApp', 'network-appliance-inc', 'NTAP');
        add('E-TRADE', 'etrade-fincl-cp', 'ETFC');
        add('Garmin Ltd', 'garmin-ltd', 'GRMN');
        add('Costco', 'costco-whsl-corp-new', 'COST');
        add('Check Point Software Tech', 'check-point-software-tech-lt', 'CHKP');
        add('Lam Research Corp', 'lam-research-corp', 'LRCX');
        add('Ciena Corp', 'ciena', 'CIEN');
        add('IAC/InterActiveCorp', 'iac-interactivecorp', 'IAC');
        add('Intuit', 'intuit', 'INTU');
        add('Expedia', 'expedia', 'EXPE');
        add('Ctripcom', 'ctrip.com-international', 'CTRP');
        add('UTStarcom Holdings', 'utstarcom-inc', 'UTSI');
        add('Cognizant', 'cognizant-technology-solutio', 'CTSH');
        add('Rambus', 'rambus-inc', 'RMBS');
        add('NII Holdings', 'nii-hldgs-inc', 'NIHD');
        add('YRC Worldwide', 'yrc-worldwide', 'YRCW');
        add('Akamai', 'akamai-technologies-inc', 'AKAM');
        add('KLA-Tencor', 'kla-tencor-corp', 'KLAC');
        add('Juniper', 'juniper-networks-inc', 'JNPR');
        add('Activision Blizzard', 'activision-inc', 'ATVI');
        add('Flex', 'flextronics-intl-ltd', 'FLEX');
        add('Amgen', 'amgen-inc', 'AMGN');
        add('Xilinx', 'xilinx-inc', 'XLNX');
        add('Expeditors Washington', 'expeditors-intl-wash-inc', 'EXPD');
        add('Electronic Arts', 'electronic-arts-inc', 'EA');
        add('JA Solar', 'ja-solar-hld', 'JASO');
        add('Patterson', 'patterson-companies-inc', 'PDCO');
        add('T Rowe', 't-rowe-price-gp', 'TROW');
        add('Biogen Inc', 'biogen-idec-inc', 'BIIB');
        add('Liberty Interactive A', 'liberty-media-inter', 'QVCA');
        add('NutriSystem', 'nutrisystems', 'NTRI');
        add('The Charles Schwab', 'charles-schwab', 'SCHW');
        add('DryShips', 'dryships', 'DRYS');
        add('Huntington Bancshares', 'huntgtn-bkshr', 'HBAN');
        add('Symantec', 'symantec-corp', 'SYMC');
        add('NVIDIA', 'nvidia-corp', 'NVDA');
        add('Stericycle', 'stericycle-inc', 'SRCL');
        add('Starbucks', 'starbucks-corp', 'SBUX');
        add('Celgene', 'celgene-corp', 'CELG');
        add('Cincinnati Financial', 'cincinnati-fin', 'CINF');
        add('Extreme', 'extreme-networks', 'EXTR');
        add('Axon Enterprise', 'taser-intl', 'AAXN');
        add('Xcerra Corp', 'ltx-credence-corp', 'XCRA');
        add('CA', 'ca-inc', 'CA');
        add('Hologic', 'hologic-inc', 'HOLX');
        add('Comcast', 'comcast-corp-new', 'CMCSA');
        add('Capstone Turbine', 'capstone-turbine-corp', 'CPST');
        add('Marvell Technology Group', 'marvell-technology-group-ltd', 'MRVL');
        add('Ballard Power Systems', 'ballard-power-systems-inc', 'BLDP');
        add('Sify', 'sify-technologies', 'SIFY');
        add('Clean Diesel Tech', 'clean-diesel-tech', 'CDTI');
        add('Royal Imtech', 'imtech', 'IMTEF');
        add('Saft Groupe', 'saft-groupe', 'SGPEF');
        add('Fox Inc', 'fox-inc', 'FOX');
        add('Medtronic', 'medtronic', 'MDT');
        add('Dover', 'dover-corp', 'DOV');
        add('Ashland Global', 'ashland-inc', 'ASH');
        add('Northrop Grumman', 'northrop-grumman', 'NOC');
        add('MGM', 'mgm-mirage', 'MGM');
        add('Vornado', 'vornado-realty', 'VNO');
        add('Mastercard', 'mastercard-cl-a', 'MA');
        add('AutoNation', 'autonation-inc', 'AN');
        add('Fluor', 'fluor-corp', 'FLR');
        add('General Dynamics', 'general-dynam', 'GD');
        add('DTE Energy', 'dte-energy', 'DTE');
        add('Analog Devices', 'analog-devices', 'ADI');
        add('VF', 'vf-corp', 'VFC');
        add('Allergan', 'actavis', 'AGN');
        add('Cardinal Health', 'cardinal-health', 'CAH');
        add('Xcel Energy', 'xcel-energy', 'XEL');
        add('DR Horton', 'd.r.-horton-inc', 'DHI');
        add('IPG', 'interpublic-grp', 'IPG');
        add('SunTrust Banks', 'sun-trust-bk', 'STI');
        add('Bemis', 'bemis-company', 'BMS');
        add('Lockheed Martin', 'lockheed-martin', 'LMT');
        add('Waters', 'waters-corp', 'WAT');
        add('Accenture', 'accenture-ltd', 'ACN');
        add('XL Group', 'xl-capital-ltd', 'XL');
        add('Dominion Resources', 'dominion-res', 'D');
        add('Exxon Mobil', 'exxon-mobil', 'XOM');
        add('Cigna', 'cigna-corp', 'CI');
        add('Piper Jaffray', 'piper-jaffray-co', 'PJC');
        add('Kinross Gold', 'kinross-gold', 'KGC');
        add('Public Service Enterprise', 'publ-svc-enter', 'PEG');
        add('NiSource', 'ni-source-inc', 'NI');
        add('Walter Energy', 'walter-industries-inc', 'WLTGQ');
        add('Yingli Green Energy', 'yingli-green', 'YGE');
        add('Zimmer Biomet', 'zimmer-hldgs', 'ZBH');
        add('CSX', 'csx-corp', 'CSX');
        add('ICE', 'intercontintlex', 'ICE');
        add('L3 Tech', 'l3-comms-hldgs', 'LLL');
        add('Praxair', 'praxair-inc', 'PX');
        add('Southwest Airlines', 'sth-west-airlines', 'LUV');
        add('Illinois Tool Works', 'illinois-tool-wk-r', 'ITW');
        add('Darden Restaurants', 'dardem-rest', 'DRI');
        add('Mattel', 'mattel-inc', 'MAT');
        add('BB&T', 'bb-t-corp', 'BBT');
        add('Cameco', 'cameco-corp', 'CCJ');
        add('Halliburton', 'halliburton-co', 'HAL');
        add('ProLogis', 'prologis', 'PLD');
        add('McCormick&Co', 'mccormick---co', 'MKC');
        add('Gap', 'gap.inc', 'GPS');
        add('Terex', 'terex-corp', 'TEX');
        add('Host Hotels Resorts', 'host-hotels---res', 'HST');
        add('Estee Lauder', 'estee-lauder', 'EL');
        add('International Paper', 'intl-paper-co', 'IP');
        add('Emerson', 'emerson-elec', 'EMR');
        add('Clorox', 'clorox-co', 'CLX');
        add('Agrium', 'agrium-inc', 'AGU');
        add('ConocoPhillips', 'conoco-phillips', 'COP');
        add('Colgate-Palmolive', 'colgate-palmo', 'CL');
        add('Raytheon', 'raytheon-co', 'RTN');
        add('Noble Corporation', 'noble-corp', 'NE');
        add('Pinnacle West Capital', 'pinnacle-west', 'PNW');
        add('Regions Financial', 'regions-fin', 'RF');
        add('CenterPoint Energy', 'centerpoint', 'CNP');
        add('MetLife', 'metlife-inc', 'MET');
        add('Exelon', 'exelon-corp', 'EXC');
        add('Baxter', 'baxter-intl', 'BAX');
        add('Alpha Natural Pref A', 'alpha-natural-resources', 'ALHAP');
        add('Occidental', 'occidental-petro', 'OXY');
        add('Sprint Corp', 'sprint-nextel-corp', 'S');
        add('Southern', 'southern-co', 'SO');
        add('Tapestry', 'coach', 'TPR');
        add('Lennar', 'lennar', 'LEN');
        add('Campbell Soup', 'campbell-soup', 'CPB');
        add('CenturyLink', 'centurylink', 'CTL');
        add('State Street', 'state-street', 'STT');
        add('Progressive', 'the-progressive', 'PGR');
        add('Harmony Gold Mining', 'harmony-gold-mng', 'HMY');
        add('Cleveland-Cliffs', 'cleveland-cliffs', 'CLF');
        add('Vulcan Materials', 'vulcan-matrls', 'VMC');
        add('CONSOL Energy', 'consol-energy', 'CNX');
        add('Parker-Hannifin', 'parkerhannifin', 'PH');
        add('Anadarko Petroleum', 'anadarko-petro', 'APC');
        add('Teck Resources B', 'teck-cominco', 'TECK');
        add('Genuine Parts', 'genuine-parts-co', 'GPC');
        add('CBRE', 'cbre', 'CBG');
        add('DuPont', 'du-pont', 'DWDP');
        add('Orix', 'orix', 'IX');
        add('Sherwin-Williams', 'sherwinwilliams', 'SHW');
        add('Pfizer', 'pfizer', 'PFE');
        add('NTT DOCOMO', 'ntt-docomo', 'DCM');
        add('Wells Fargo&Co', 'wells-fargo', 'WFC');
        add('Manitowoc', 'manitowoc-co.', 'MTW');
        add('Wal-Mart Stores', 'wal-mart-stores', 'WMT');
        add('Edison', 'edison-intl', 'EIX');
        add('KB Home', 'kb-home', 'KBH');
        add('Snap-On', 'snapon-inc', 'SNA');
        add('Allegheny Technologies', 'allegheny-tech', 'ATI');
        add('Xerox', 'xerox-corp', 'XRX');
        add('Equifax', 'equifax-inc', 'EFX');
        add('Gold Fields ADR', 'gold-fields-lts', 'GFI');
        add('Konami Holdings', 'konami', 'KNMCY');
        add('McKesson', 'mckesson-corp', 'MCK');
        add('Entergy', 'entergy-corp', 'ETR');
        add('CMS Energy', 'cms-energy-corp', 'CMS');
        add('Honda Motor ADR', 'honda', 'HMC');
        add('Ameriprise Financial', 'ameriprise-fincl', 'AMP');
        add('AIG', 'american-intl-group', 'AIG');
        add('Ralph Lauren', 'polo-ralph-laur', 'RL');
        add('Leggett&Platt', 'leggett---platt', 'LEG');
        add('L Brands', 'limited-brands', 'LB');
        add('IFF', 'intl-flav---frag', 'IFF');
        add('Petroleo Brasileiro Petrobras ADR', 'petroleo-bras', 'PBR');
        add('M/I Homes', 'm-i-homes-inc', 'MHO');
        add('WW Grainger', 'w-w-grainger-inc', 'GWW');
        add('JC Penney', 'j-c-penney-co', 'JCP');
        add('Diamond Offshore Drilling', 'diamond-offshore', 'DO');
        add('Constellation Brands', 'constellation-a', 'STZ');
        add('China Digital TV', 'china-dig-tv-hld', 'STVVY');
        add('American Tower', 'amer-tower-corp', 'AMT');
        add('Grupo Televisa ADR', 'grupo-televisa-sa-adr', 'TV');
        add('Philip Morris', 'philip-morris-intl', 'PM');
        add('Fidelity National Info', 'fidelity-natl-in', 'FIS');
        add('Altria', 'altria-group', 'MO');
        add('El Paso Energy Capital Trust I', 'el-paso-corp', 'EP_pc');
        add('Stewart Information Services', 'stewart-information-services-corp', 'STC');
        add('CBS', 'cbs-corp-cl-b', 'CBS');
        add('Ball', 'ball-corp', 'BLL');
        add('Hartford', 'hartford-finl', 'HIG');
        add('AK Steel', 'ak-steel-holding-corp', 'AKS');
        add('Hershey', 'hershey-co', 'HSY');
        add('DDR', 'ddr', 'DDR');
        add('DXC Technology', 'comp-science', 'DXC');
        add('Morgan Stanley', 'morgan-stanley', 'MS');
        add('PNC Financial', 'pnc-fin-serv', 'PNC');
        add('Waste Management', 'waste-managemnt', 'WM');
        add('AmerisourceBergen', 'amerisourcebergn', 'ABC');
        add('Assurant', 'assurant', 'AIZ');
        add('Kroger', 'kroger-co', 'KR');
        add('Molson Coors Brewing', 'molson-coors', 'TAP');
        add('Home Depot', 'home-depot', 'HD');
        add('Becton Dickinson', 'becton-dickinsn', 'BDX');
        add('Arch Coal', 'arch-coal-inc', 'ARCH');
        add('JM Smucker', 'jm-smucker-co', 'SJM');
        add('CR Bard', 'c-r-bard', 'BCR');
        add('VMware', 'vm-ware-inc', 'VMW');
        add('Sealed Air', 'sealed-air', 'SEE');
        add('Best Buy', 'best-buy', 'BBY');
        add('Andeavor', 'tesoro', 'ANDV');
        add('Archer-Daniels-Midland', 'archer-daniels-mid', 'ADM');
        add('Brown Forman', 'brown-forman-b', 'BFb');
        add('IBM', 'ibm', 'IBM');
        add('Union Pacific', 'union-pacific', 'UNP');
        add('China Fund', 'china-fund-inc', 'CHN');
        add('Sony ADR', 'sony', 'SNE');
        add('Ryder System', 'ryder-system-inc', 'R');
        add('SLM', 'slm-corporation', 'SLM');
        add('Micron', 'micron-tech', 'MU');
        add('Avery Dennison', 'avery-dennison', 'AVY');
        add('Weatherford', 'weatherfgord-intl', 'WFT');
        add('Marathon Oil', 'marathon-oil', 'MRO');
        add('CF Industries', 'cf-industries', 'CF');
        add('Apache', 'apache-corp', 'APA');
        add('Duke Energy', 'duke-energy', 'DUK');
        add('KeyCorp', 'keycorp-new', 'KEY');
        add('Teradata', 'teradata', 'TDC');
        add('Synovus', 'synovus-finan', 'SNV');
        add('Wheaton Precious Metals', 'silver-wheaton-corp', 'WPM');
        add('ARO Liquidation', 'aeropostale', 'AROPQ');
        add('Laboratory of America', 'laboratory-corp-of-amer', 'LH');
        add('Boston Properties', 'boston-ppty', 'BXP');
        add('Western Digital', 'western-digital', 'WDC');
        add('PPG Industries', 'ppg-industries', 'PPG');
        add('S&P Global', 'mcgraw-hill', 'SPGI');
        add('Abercrombie&Fitch', 'aberc-fitch-a', 'ANF');
        add('Williams', 'williams-cos', 'WMB');
        add('Anthem Inc', 'wellpoint-inc', 'ANTM');
        add('Brunswick', 'brunswick-corp', 'BC');
        add('Jacobs Engineering', 'jacobs-engineer', 'JEC');
        add('Eastman Chemical', 'eastman-chem', 'EMN');
        add('Verizon', 'verizon-communications', 'VZ');
        add('Nucor', 'nucor', 'NUE');
        add('Omnicom', 'omnicom-gp-inc', 'OMC');
        add('NewYork Times', 'new-york-times', 'NYT');
        add('Lincoln National', 'lincoln-natl', 'LNC');
        add('UBS Group', 'ubs-group-n?cid=8132', 'UBS');
        add('National Oilwell Varco', 'ntl-oilwell-varc', 'NOV');
        add('AvalonBay', 'avalonbay-comm', 'AVB');
        add('Marriott Int', 'marriott-intl', 'MAR');
        add('Ingersoll-Rand', 'ingersoll-rand', 'IR');
        add('Bristol-Myers Squibb', 'bristol-myer-squiib', 'BMY');
        add('Genworth', 'genworth-finl', 'GNW');
        add('American Electric Power', 'american-electric', 'AEP');
        add('Thermo Fisher Scientific', 'thermo-fisher-sc', 'TMO');
        add('Kohl’s', 'kohls-corp', 'KSS');
        add('Newmont Mining', 'newmont-mining', 'NEM');
        add('Total System Services', 'total-sys-svcs', 'TSS');
        add('Varian', 'varian-medical', 'VAR');
        add('Graham Hld Co', 'washington-post-co.', 'GHC');
        add('Tata Motors ADR', 'tata-motors', 'TTM');
        add('Sunedison Inc', 'sunedison-inc', 'SUNEQ');
        add('Public Storage', 'public-stg-mld', 'PSA');
        add('The Travelers', 'the-travelers-co', 'TRV');
        add('Stanley Black Decker', 'stanley-works', 'SWK');
        add('Potash Saskatchewan', 'potash', 'POT');
        add('MBIA', 'mbia-inc', 'MBI');
        add('Aetna', 'aetna-inc', 'AET');
        add('HDFC Bank ADR', 'hdfc-bank', 'HDB');
        add('Nippon', 'nippon-telegraph', 'NTTYY');
        add('Franklin Resources', 'franklin-res', 'BEN');
        add('Rockwell Collins', 'rockwe-coll', 'COL');
        add('Humana', 'humana-inc', 'HUM');
        add('H&R Block', 'h---r-block-inc', 'HRB');
        add('Viacom B', 'viacom-cl-b', 'VIAB');
        add('Unum', 'unum-group', 'UNM');
        add('Chubb', 'chubb-corp', 'CB');
        add('Leucadia National', 'leucadia-natl', 'LUK');
        add('J&J', 'johnson-johnson', 'JNJ');
        add('Time Warner', 'time-warner', 'TWX');
        add('Tyson Foods', 'tyson-foods', 'TSN');
        add('Target', 'target', 'TGT');
        add('Jabil Circuit', 'jabil-circuit', 'JBL');
        add('American Express', 'american-express', 'AXP');
        add('America Movil ADR', 'america-movil', 'AMX');
        add('Masco', 'masco-corp', 'MAS');
        add('United States Steel', 'us-steel-corp', 'X');
        add('Stryker', 'stryker', 'SYK');
        add('Mitsubishi UFJ Financial ADR', 'mits-ufj-financial-grp', 'MTU');
        add('Discover', 'discover-financl', 'DFS');
        add('Prudential Financial', 'prudential-fin', 'PRU');
        add('Abbott Labs', 'abbott-laboratories', 'ABT');
        add('General Electric', 'general-electric', 'GE');
        add('Oi ADR Pref', 'oi', 'OIBRQ');
        add('Meredith', 'meredith-corp', 'MDP');
        add('Quest Diagnostics', 'quest-diag', 'DGX');
        add('United Parcel Service', 'united-parcel', 'UPS');
        add('Yamana Gold', 'yamana-gold', 'AUY');
        add('CVS Health Corp', 'cvs-corp', 'CVS');
        add('ITT', 'itt-corp', 'ITT');
        add('PPL', 'ppl-corp', 'PPL');
        add('Dean Foods', 'dean-foods-co', 'DF');
        add('Robert Half', 'robert-half-intl', 'RHI');
        add('Convergys', 'convergys-cp', 'CVG');
        add('Simon Property', 'simon-prop-grp', 'SPG');
        add('ICICI Bank ADR', 'icici-bank', 'IBN');
        add('Big Lots', 'big-lots-inc', 'BIG');
        add('Avon Products', 'avon-products', 'AVP');
        add('Johnson Controls', 'johnson-controls', 'JCI');
        add('Cummins', 'cummins-inc', 'CMI');
        add('Allstate', 'allstate-corporation', 'ALL');
        add('Sempra Energy', 'sempra-energy', 'SRE');
        add('Devon Energy', 'devon-energy', 'DVN');
        add('ConAgra Foods', 'conagra-foods', 'CAG');
        add('TJX', 'tjx-co-inc', 'TJX');
        add('Whirlpool', 'whirl-pool-corp', 'WHR');
        add('Range Resources', 'range-resources-corp', 'RRC');
        add('FirstEnergy', 'first-energy', 'FE');
        add('Hovnanian Enterprises', 'hovnanian-enter', 'HOV');
        add('Torchmark', 'torchmark-corp', 'TMK');
        add('United Technologies', 'united-tech', 'UTX');
        add('PulteGroup', 'pulte-homes-inc', 'PHM');
        add('Wyndham', 'wyndham-world', 'WYN');
        add('Valero Energy', 'valero-energy', 'VLO');
        add('IGT', 'intl-game-tech', 'IGT');
        add('Noble Energy', 'noble-energy', 'NBL');
        add('Supervalu', 'supervalu-inc', 'SVU');
        add('Boston Scientific', 'boston-scien-cp', 'BSX');
        add('Frontier Communications', 'frontier-communications-corp', 'FTR');
        add('Capital One Financial', 'capital-one', 'COF');
        add('Pacific Gas&Electric', 'pacific-gas-electric', 'PCG');
        add('Norfolk Southern', 'norfolk-southern', 'NSC');
        add('Aflac', 'aflac-inc', 'AFL');
        add('Chesapeake Energy', 'chesapeake-ener', 'CHK');
        add('Harley-Davidson', 'harley-davidson', 'HOG');
        add('Equity Residential', 'eq-resident', 'EQR');
        add('Pitney Bowes', 'pitney-bowes-inc', 'PBI');
        add('Air Products', 'air-prods---chem', 'APD');
        add('First Horizon National', 'first-horizon-ntl', 'FHN');
        add('Principal', 'principal-fin', 'PFG');
        add('Texas Instruments', 'texas-instru', 'TXN');
        add('Grupo Aeroportuario Sureste', 'grupo-aeroportuario-sur-adr', 'ASR');
        add('HP Inc', 'hewlett-pack', 'HPQ');
        add('Coca-Cola EU Partners', 'coca-cola-ent', 'CCE');
        add('Honeywell', 'honeywell-intl', 'HON');
        add('Nomura ADR', 'nomura-holdings', 'NMR');
        add('AMD', 'adv-micro-device', 'AMD');
        add('M&T Bank', 'm-t-bank-corp', 'MTB');
        add('NCR', 'ncr-corp', 'NCR');
        add('Mosaic', 'mosaic-company', 'MOS');
        add('PerkinElmer', 'perkinelmer', 'PKI');
        add('Las Vegas Sands', 'las-vegas-sands', 'LVS');
        add('Freeport-McMoran', 'freeport-mcm', 'FCX');
        add('AutoZone', 'autozone-inc', 'AZO');
        add('Nabors Industries', 'nabors-inds', 'NBR');
        add('Sysco', 'sysco-corp', 'SYY');
        add('Tenet Healthcare', 'tenet-healthcare', 'THC');
        add('Ameren', 'ameren-corp', 'AEE');
        add('Industrias Bachoco ADR', 'industrias-bachoco-sab-adr', 'IBA');
        add('Eaton', 'eaton', 'ETN');
        add('MFC', 'mfc-industrial', 'MFCB');
        add('Coca Cola Femsa ADR', 'coca-cola-femsa-adr', 'KOF');
        add('Salesforce.com', 'salesforce-com', 'CRM');
        add('Actuant', 'actuant-corp', 'ATU');
        add('Consolidated Edison', 'cocnsol-edison', 'ED');
        add('The AES', 'aes-corp', 'AES');
        add('Transocean', 'transocea-ltd', 'RIG');
        add('Apartment Invest', 'apt-inv-manage', 'AIV');
        add('Rowan', 'rowan-co-inc', 'RDC');
        add('Textron', 'textron-inc', 'TXT');
        add('Gruma SAB de CV', 'gruma-sab-adr', 'GPAGF');
        add('Unisys', 'unisys-corp', 'UIS');
        add('Federated Investors', 'fed-investors', 'FII');
        add('Viacom', 'viacom-inc', 'VIA');
        add('US Bancorp', 'us-bancorp', 'USB');
        add('Comerica', 'comerica-inc', 'CMA');
        add('Ensco PLC', 'ensco-intl', 'ESV');
        add('Tiffany&Co', 'tiffany---co', 'TIF');
        add('Visa', 'visa-inc', 'V');
        add('MGIC Investment', 'mgic-inv', 'MTG');
        add('Baker Hughes A', 'baker-hughes', 'BHGE');
        add('Toyota Motor ADR', 'toyota', 'TM');
        add('Western Union', 'western-union', 'WU');
        add('Canon ADR', 'canon', 'CAJ');
        add('Hess', 'hess-corp', 'HES');
        add('Yum! Brands', 'yum!-brands-inc', 'YUM');
        add('Marsh&McLennan', 'marsh---mclennan', 'MMC');
        add('Kyocera', 'kyocera', 'KYO');
        add('LDK Solar', 'ldk-solar-co', 'LDKYQ');
        add('Kellogg', 'kellogg-co.', 'K');
        add('Kimco', 'kimco-realty', 'KIM');
        add('Ecolab', 'ecolab-inc', 'ECL');
        add('Nordstrom', 'nordstrom-inc', 'JWN');
        add('EOG Resources', 'eog-resources', 'EOG');
        add('Newell Brands', 'newell-rubber', 'NWL');
        add('Aon', 'aon-corp', 'AON');
        add('Hasbro', 'hasbro-inc', 'HAS');
        add('Bank of NY Mellon', 'bk-of-ny', 'BK');
        add('Wipro ADR', 'wipro', 'WIT');
        add('Schlumberger', 'schlumberger-ltd', 'SLB');
        add('Walgreens Boots Alliance', 'walgreen-co', 'WBA');
        add('Rockwell Automation', 'rockwell-automat', 'ROK');
        add('PepsiCo', 'pepsico', 'PEP');
        add('UnitedHealth', 'united-health-group', 'UNH');
        add('Allergan Pref', 'allergan-inc', 'AGN_pa');
        add('Teradyne', 'teradyne-inc', 'TER');
        add('Murphy Oil', 'murphy-oil-corp', 'MUR');
        add('Mizuho Financial ADR', 'mizuho', 'MFG');
        add('Dillards', 'dillards', 'DDS');
        add('Danaher', 'danaher-corp', 'DHR');
        add('FLIR Systems', 'flir-systems', 'FLIR');
        add('SunPower', 'sunpower-corporation', 'SPWR');
        add('Seagate Technology', 'seagate-technology', 'STX');
        add('Agilent Technologies', 'agilent-tech', 'A');
        add('Cemex ADR', 'cemex-sab-de-cv-adr', 'CX');
        add('Delta Air Lines', 'delta-air-lines-new', 'DAL');
        add('Macy’s Inc', 'macys', 'M');
        add('Moodys', 'moodys-corp', 'MCO');
        add('Nike', 'nike', 'NKE');
        add('Dr Reddys Labs', 'dr.-reddys-laboratories', 'RDY');
        add('Lindsay', 'lindsay-corporation', 'LNN');
        add('Monsanto', 'monsanto', 'MON');
        add('Procter&Gamble', 'procter-gamble', 'PG');
        add('Weyerhaeuser', 'weyerhaeuser', 'WY');
        add('Empresas ICA ADR', 'empresas-ica-soc-con', 'ICAYY');
        add('ADP', 'auto-data-process', 'ADP');
        add('Red Hat', 'red-hat-inc', 'RHT');
        add('Denbury Resources', 'denbury-resources-inc', 'DNR');
        add('Allscripts', 'allscripts-misys-healthcre-solution', 'MDRX');
        add('Reliance Steel&Aluminum', 'reliance-steel---aluminum-co.', 'RS');
        add('SSR Mining', 'silver-standard-resources', 'SSRM');
        add('Southwestern Energy', 'southwestern-energy-company', 'SWN');
        add('Carters', 'carters-inc', 'CRI');
        add('Dr Pepper Snapple', 'dr-pepper-snapple', 'DPS');
        add('Lowe’s', 'lowes-companies', 'LOW');
        add('Ampal American Israel', 'ampal-am-israel', 'AMPLQ');
        add('The Middleby', 'the-middleby-corp', 'MIDD');
        add('VALE', 'vale-s.a.--americ', 'VALE');
        add('CPFL Energia ADR', 'cpfl-energia-s.a.', 'CPL');
        add('United Continental', 'united-continenta', 'UAL');
        add('Netflix', 'netflix,-inc.', 'NFLX');
        add('News Corp', 'news-corporation', 'NWS');
        add('Tupperware Brands', 'tupperware-brands', 'TUP');
        add('Equinix', 'equinix,-inc.', 'EQIX');
        add('Cerner', 'cerner-corporatio', 'CERN');
        add('China Green Agriculture', 'china-green', 'CGA');
        add('Priceline.com', 'priceline.com-inc', 'PCLN');
        add('O\'Reilly', 'oreilly-automotive', 'ORLY');
        add('Seattle Genetics', 'seattle-genetics,', 'SGEN');
        add('BlackRock', 'blackrock,-inc.-c', 'BLK');
        add('Cabot', 'cabot-microelectr', 'CCMP');
        add('CME Group', 'cme-group-inc.', 'CME');
        add('Illumina Inc', 'illumina,-inc.', 'ILMN');
        add('JB Hunt', 'j.b.-hunt-transpo', 'JBHT');
        add('Loews', 'loews-corporation', 'L');
        add('Maxim', 'maxim-integrated', 'MXIM');
        add('Rogers Communications', 'rogers-communicat', 'RCI');
        add('Urban Outfitters', 'urban-outfitters', 'URBN');
        add('EW Scripps', 'e.w.-scripps-comp', 'SSP');
        add('Oshkosh', 'oshkosh-corporati', 'OSK');
        add('NextEra Energy', 'nextera-energy-inc', 'NEE');
        add('Central Fund of Canada', 'central-fund-of-canada-limited', 'CEF');
        add('Sonic', 'sonic-corp.', 'SONC');
        add('First Solar', 'first-solar-inc', 'FSLR');
        add('Mylan', 'mylan-inc', 'MYL');
        add('Makita', 'makita-corp', 'MKTAY');
        add('Mitsui & Company', 'mitsui---company-ltd', 'MITSY');
        add('World Poker Fund Holdings', 'mmk_mm', 'WPFH');
        add('Polymetal International', 'polymetal?cid=13751', 'POYYF');
        add('F5 Networks', 'f5-networks-inc', 'FFIV');
        add('Edwards Lifesciences', 'edward-lifescience', 'EW');
        add('News Corp A', 'news-corp.', 'NWSA');
        add('Alexion', 'alexion-pharmaceuticals,-inc.', 'ALXN');
        add('Amphenol', 'amphenol-corp', 'APH');
        add('Berkshire Hathaway B', 'berkshire-hathaway', 'BRKb');
        add('Cabot Oil&Gas', 'cabot-oil---gas', 'COG');
        add('CarMax', 'carmax-inc', 'KMX');
        add('Chipotle Mexican Grill', 'chipotle-mexican-grill-inc', 'CMG');
        add('DaVita', 'davita-inc', 'DVA');
        add('Adtalem Education', 'devry-inc', 'ATGE');
        add('Dun&Bradstreet', 'dun---bradstreet', 'DNB');
        add('EQT', 'eqt-corporation', 'EQT');
        add('FMC', 'fmc-corp', 'FMC');
        add('TechnipFMC', 'fmc-technologies-inc', 'FTI');
        add('Flowserve', 'flowserve-corp', 'FLS');
        add('GameStop Corp', 'gamestop-corp', 'GME');
        add('Harris', 'harris-corporation', 'HRS');
        add('HCP', 'hcp-inc', 'HCP');
        add('Welltower Inc', 'health-care-reit', 'HCN');
        add('Helmerich&Payne', 'helmerich---payne', 'HP');
        add('Hormel Foods', 'hormel-foods-corp', 'HRL');
        add('Invesco', 'invesco-ltd', 'IVZ');
        add('Iron Mountain', 'iron-mountain-inc', 'IRM');
        add('Newfield Exploration', 'newfield-exploration-co.', 'NFX');
        add('Eversource Energy', 'northeast-utilities', 'ES');
        add('NRG', 'nrg-energy-inc', 'NRG');
        add('ONEOK', 'oneok', 'OKE');
        add('Owens-Illinois', 'owens-illinois-inc', 'OI');
        add('Pioneer Natural Resources', 'pioneer-natural-resources', 'PXD');
        add('QEP Resources', 'qep-resources', 'QEP');
        add('Republic Services', 'republic-services-inc', 'RSG');
        add('Roper Technologies', 'roper-industries', 'ROP');
        add('Scana', 'scana-corp', 'SCG');
        add('Scripps Networks', 'scripps-networks-interactive', 'SNI');
        add('Ventas', 'ventas-inc', 'VTR');
        add('WEC Energy', 'wisconsin-energy-corp', 'WEC');
        add('RR Donnelley & Sons', 'donnelley,-r.r.---sons', 'RRD');
        add('Barrick Gold', 'barrick-gold-corp.', 'ABX');
        add('Agnico Eagle Mines', 'agnico-eagle-mines', 'AEM');
        add('Autoliv', 'autoliv-inc.', 'ALV');
        add('The Blackstone', 'the-blackstone-group', 'BX');
        add('Chimera Investment', 'chimera-investment-corp', 'CIM');
        add('Cohn&Steers', 'cohen---steers-inc.', 'CNS');
        add('Carbo Ceramics', 'carbo-ceramics-inc.', 'CRR');
        add('3D Systems', '3d-systems-corporation', 'DDD');
        add('Interoil', 'interoil?cid=13940', 'IROIF');
        add('Lazard', 'lazard-ltd', 'LAZ');
        add('Magna International', 'magna-international', 'MGA');
        add('Marathon Petroleum', 'marathon-petroleum-corp.', 'MPC');
        add('Nustar', 'nustar-energy-l.p.', 'NS');
        add('Belmond', 'orient-express-hotels', 'BEL');
        add('Overseas Shipholding', 'overseas-shipholding-group', 'OSG');
        add('Pandora Media', 'pandora-media', 'P');
        add('RPC', 'rpc-inc.', 'RES');
        add('Southern Copper', 'southern-copper-corp.', 'SCCO');
        add('Sandridge Energy', 'sandridge-energy', 'SD');
        add('Titan', 'titan-international', 'TWI');
        add('Under Armour A', 'under-armour', 'UAA');
        add('Valeant Pharmaceuticals', 'valeant-pharma', 'VRX');
        add('Aqua America', 'aqua-america-inc.', 'WTR');
        add('ADTRAN', 'adtran-inc.', 'ADTN');
        add('Advanced Energy', 'advanced-energy', 'AEIS');
        add('AirMedia', 'airmedia-group', 'AMCN');
        add('Arena Pharma', 'arena-pharma', 'ARNA');
        add('ARRIS Group Inc', 'arris-group-inc.', 'ARRS');
        add('Broadcom', 'avago-technologies', 'AVGO');
        add('Brocade', 'brocade-communications', 'BRCD');
        add('Celsion', 'celsion-corp.', 'CLSN');
        add('Cree', 'cree-inc.', 'CREE');
        add('Cirrus', 'cirrus-logic-inc.', 'CRUS');
        add('Dunkin Brands', 'dunkin-brands-group', 'DNKN');
        add('Entegris', 'entegris-inc.', 'ENTG');
        add('The Hain Celestial', 'hain-celestial-group', 'HAIN');
        add('Internet Initiative Japan ADR', 'internet-initiative-japan', 'IIJI');
        add('IPG Photonics', 'ipg-photonics-corp.', 'IPGP');
        add('Ionis Pharma', 'isis-pharma', 'IONS');
        add('Itron', 'itron-inc.', 'ITRI');
        add('L&L Energy', 'l-l-energy', 'LLEN');
        add('ManTech', 'mantech-international', 'MANT');
        add('Merriman Inc', 'merriman-holdings', 'MERR');
        add('Motorcar Parts', 'motorcar-parts-of-america', 'MPAA');
        add('Nuance Communications', 'nuance-communications', 'NUAN');
        add('NXP', 'nxp-semiconductors', 'NXPI');
        add('QuickLogic', 'quicklogic-corp.', 'QUIK');
        add('Radware Ltd', 'radware-ltd.', 'RDWR');
        add('Royal Gold', 'royal-gold-inc.', 'RGLD');
        add('Tesla', 'tesla-motors', 'TSLA');
        add('Take-Two', 'take-two-interactive', 'TTWO');
        add('Wacoal', 'wacoal-holdings-corp.', 'WACLY');
        add('MecklerMedia Corp', 'webmediabrands-inc', 'MECK');
        add('Яндекс', 'yandex', 'YNDX');
        add('Brammer', 'brammer', 'BMMEF');
        add('New Zealand Oil Gas', 'new-zealand-oil---gas-ltd', 'NZEOF');
        add('Unilife ADR', 'unilife-corporation', 'UNISZ');
        add('Beadell Res Ltd', 'beadell-res-ltd?cid=14582', 'BDREF');
        add('Regis Resources Ltd', 'regis-resources-ltd?cid=14595', 'RGRNF');
        add('TNT Express', 'tnt-express', 'TNTEF');
        add('Dollar Tree', 'dollar-tree-inc', 'DLTR');
        add('Espirito Santo SA', 'espirito-santo-re', 'ESFOF');
        add('Kleinwort Benson', 'rhj-international', 'RHJIF');
        add('Atlantic American', 'atlantic-american', 'AAME');
        add('AAON', 'aaon', 'AAON');
        add('Atlas Air', 'atlas-air-worldwide', 'AAWW');
        add('ABAXIS', 'abaxis', 'ABAX');
        add('Ameris', 'ameris-bancorp', 'ABCB');
        add('Cambium', 'cambium-learning', 'ABCD');
        add('The Advisory Board', 'the-advisory-boar', 'ABCO');
        add('ArcBest Corp', 'arkansas-best-corp', 'ARCB');
        add('ARCA Biopharma', 'arca-biopharma', 'ABIO');
        add('ABIOMED', 'abiomed', 'ABMD');
        add('Autobytel', 'autobytel-inc', 'AUTO');
        add('ACADIA', 'acadia-pharmaceuticals', 'ACAD');
        add('Aceto', 'aceto-corp', 'ACET');
        add('Atlantic Coast Federal', 'atlantic-coast-federal-corp', 'ACFC');
        add('Acorn', 'acorn-energy', 'ACFN');
        add('Acadia Healthcare', 'acadia-healthcare', 'ACHC');
        add('Achillion', 'achillion-pharmaceuticals', 'ACHN');
        add('ACI Worldwide', 'aci-worldwide', 'ACIW');
        add('Axcelis', 'axcelis-tech', 'ACLS');
        add('ACNB', 'acnb-corp', 'ACNB');
        add('Acorda', 'acorda-therapeutics', 'ACOR');
        add('AcelRx', 'acelrx-pharmaceuticals', 'ACRX');
        add('Acacia Research', 'acacia-research-corp', 'ACTG');
        add('Acura Pharma', 'acura-pharmaceuticals', 'ACUR');
        add('Acxiom', 'acxiom-inc', 'ACXM');
        add('Authentidate', 'authentidate-hold', 'ADAT');
        add('ADES', 'ada-es', 'ADES');
        add('Addus', 'addus-homecare', 'ADUS');
        add('Aegion', 'aegion-corp', 'AEGN');
        add('Aehr Test Systems', 'aehr-test-systems', 'AEHR');
        add('LiNiu Tech', 'iao-kun-group-hld', 'LINU');
        add('American Electric', 'american-electric-tech', 'AETI');
        add('ADDvantage', 'addvantage-technologies', 'AEY');
        add('Aeterna Zentaris', 'aeterna-zentaris-inc?cid=15348', 'AEZS');
        add('Almost Family', 'almost-family-inc', 'AFAM');
        add('Athens Bancshares', 'athens-bancshares', 'AFCB');
        add('AmTrust', 'amtrust-financial', 'AFSI');
        add('Agenus', 'agenus-inc', 'AGEN');
        add('Argo Group Int', 'argo-group-intern', 'AGII');
        add('AGNC Invest', 'american-capital-agency', 'AGNC');
        add('Agilysys', 'agilysys', 'AGYS');
        add('Alliances', 'alliance-holdings', 'AHGP');
        add('Allied Healthcare', 'allied-healthcare', 'AHPI');
        add('Altra', 'altra-holdings', 'AIMC');
        add('Air T', 'air-t', 'AIRT');
        add('Akorn', 'akorn', 'AKRX');
        add('Alico', 'alico', 'ALCO');
        add('Align', 'align-technology', 'ALGN');
        add('Allegiant', 'allegiant-travel', 'ALGT');
        add('Alimera', 'alimera-sciences', 'ALIM');
        add('Alkermes Plc', 'alkermes-plc', 'ALKS');
        add('Allot Communications', 'allot-communications-ta?cid=15373', 'ALLT');
        add('Alnylam', 'alnylam-pharmaceuticals', 'ALNY');
        add('Analogic', 'analogic-corp', 'ALOG');
        add('AstroNova', 'astro-med', 'ALOT');
        add('Alaska Communications', 'alaska-communications', 'ALSK');
        add('AMAG', 'amag-pharm', 'AMAG');
        add('Ambient', 'ambient-corp', 'AMBTQ');
        add('Andatee China Marine', 'andatee-china-marine', 'AMCF');
        add('Amedisys', 'amedisys-inc', 'AMED');
        add('Amkor', 'amkor-technology', 'AMKR');
        add('American National Bankshares', 'american-national-bankshares', 'AMNB');
        add('Allied Motion', 'allied-motion-tech', 'AMOT');
        add('America Movil ADR A', 'america-movil-sab-de-cv', 'AMOV');
        add('American River', 'american-river-bankshares', 'AMRB');
        add('Amyris', 'amyris', 'AMRS');
        add('American Superconductor', 'american-superconductor', 'AMSC');
        add('AMERISAFE', 'amerisafe', 'AMSF');
        add('American Software', 'american-software', 'AMSWA');
        add('Ameritrans Capital', 'ameritrans-capital', 'AMTCQ');
        add('TD Ameritrade', 'td-ameritrade-hol', 'AMTD');
        add('American Woodmark', 'american-woodmark', 'AMWD');
        add('American National Insurance', 'american-national-insurance', 'ANAT');
        add('Anchor', 'anchor-bancorp', 'ANCB');
        add('American Caresource', 'american-caresource', 'GNOW');
        add('Access National', 'access-national-corp', 'ANCX');
        add('The Andersons', 'the-andersons', 'ANDE');
        add('MGC Diagnostics', 'mgc-diagnostics', 'MGCD');
        add('AngioDynamics', 'angiodynamics', 'ANGO');
        add('Anika', 'anika-therapeutics', 'ANIK');
        add('ANSYS', 'ansys', 'ANSS');
        add('Anthera Pharma', 'anthera-pharmaceuticals', 'ANTH');
        add('Alpha & Omega Semiconductor', 'alpha-and-omega', 'AOSL');
        add('American Public Education', 'american-public-education', 'APEI');
        add('Apogee', 'apogee-enterprise', 'APOG');
        add('Riot Blockchain', 'venaxis', 'RIOT');
        add('Apricus Biosciences', 'apricus-biosciences', 'APRI');
        add('IRSA Propiedades ADR', 'alto-palermo-sa', 'IRCP');
        add('Asia Pacific Wire & Cable', 'asia-pacific-wire', 'APWC');
        add('Accuray', 'accuray-incorped', 'ARAY');
        add('Appliance Recycling', 'appliance-recycling', 'ARCI');
        add('Vereit', 'american-realty-c', 'VER');
        add('ARC Group', 'arc-wireless', 'ARCW');
        add('Approach Resources', 'approach-resource', 'AREX');
        add('Gentherm', 'gentherm', 'THRM');
        add('American Railcar', 'american-railcar', 'ARII');
        add('Ark Restaurants', 'ark-restaurants-corp', 'ARKR');
        add('Alliance Resource', 'alliance-resource', 'ARLP');
        add('Arrow', 'arrow-financial-corp', 'AROW');
        add('ArQule', 'arqule', 'ARQL');
        add('Array BioPharma', 'array-biopharma-inc', 'ARRY');
        add('Trecora Resources', 'arabian-american', 'TREC');
        add('Artesian', 'artesian-resource', 'ARTNA');
        add('Arts-Way', 'arts-way-manufacturing', 'ARTW');
        add('Arotech', 'arotech-corp', 'ARTX');
        add('Arrowhead Pharma', 'arrowhead-research-corp', 'ARWR');
        add('Associated Banc-Corp', 'associated-banc-corp', 'ASB');
        add('Ascent Capital', 'ascent-capital', 'ASCMA');
        add('Asta Funding', 'asta-funding', 'ASFI');
        add('On Assignment, Inc', 'on-assignment', 'ASGN');
        add('ASM ADR', 'asm-international-nv', 'ASMIY');
        add('Ascena Retail', 'ascena-retail', 'ASNA');
        add('AmeriServ', 'ameriserv', 'ASRV');
        add('Astrotech', 'astrotech-corp', 'ASTC');
        add('Astec', 'astec-industries', 'ASTE');
        add('Ascent Solar', 'ascent-solar-tech', 'ASTI');
        add('Vericel Corp Ord', 'aastrom-bioscienc', 'VCEL');
        add('Asure', 'asure-software-inc', 'ASUR');
        add('Amtech', 'amtech-systems', 'ASYS');
        add('ATA', 'ata-inc', 'ATAI');
        add('America First Tax', 'america-first-tax', 'ATAX');
        add('Astea', 'astea--international', 'ATEA');
        add('Alphatecs', 'alphatec-holdings', 'ATEC');
        add('athenahealth', 'athenahealth', 'ATHN');
        add('Athersys', 'athersys', 'ATHX');
        add('Ames', 'ames-national-corp', 'ATLO');
        add('ATN Int', 'atlantic-tele-net', 'ATNI');
        add('AtriCure', 'atricure', 'ATRC');
        add('ATRION', 'atrion-corp', 'ATRI');
        add('ATRM Holdings', 'aetrium-inc', 'ATRM');
        add('Astronics', 'astronics-corp', 'ATRO');
        add('Auburn', 'auburn-national-b', 'AUBN');
        add('AudioCodes', 'audiocodes?cid=15499', 'AUDC');
        add('AeroVironment', 'aerovironment', 'AVAV');
        add('Diversicare', 'diversicare', 'DVCR');
        add('AVEO', 'aveo-pharmaceuticals', 'AVEO');
        add('Avid', 'avid-technology', 'AVID');
        add('Sarepta', 'sarepta', 'SRPT');
        add('Aviat', 'aviat-networks', 'AVNW');
        add('A V Homes', 'a-v-homes', 'AVHI');
        add('Aware', 'aware', 'AWRE');
        add('Abraxas Petroleum', 'abraxas-petroleum', 'AXAS');
        add('AXT', 'axt-inc', 'AXTI');
        add('Natus', 'natus-medical-inc', 'BABY');
        add('Banc of California', 'banc-of-california', 'BANC');
        add('BancFirst', 'bancfirst-corp', 'BANF');
        add('Banner', 'banner-corp', 'BANR');
        add('Bioanalytical Systems', 'bioanalytical-sys', 'BASI');
        add('Hope Bancorp', 'bbcn-bancorp', 'HOPE');
        add('BreitBurn', 'breitburn-energy', 'BBEPQ');
        add('Beasley', 'beasley-broadcast', 'BBGI');
        add('Black Box', 'black-box-corp', 'BBOX');
        add('Bravo Brio', 'bravo-brio-restau', 'BBRG');
        add('Barrett', 'barrett-business', 'BBSI');
        add('BCB Bancorp', 'bcb-bancorp', 'BCBP');
        add('B Communications', 'b-communication?cid=15533', 'BCOM');
        add('Balchem', 'balchem-corp', 'BCPC');
        add('BioCryst', 'biocryst-pharmaceuticals', 'BCRX');
        add('Black Diamond', 'black-diamond', 'CLAR');
        add('Bridge Bancorp', 'bridge-bancorp', 'BDGE');
        add('Birner', 'birner-dental-man', 'BDMS');
        add('BioDelivery Sciences', 'biodelivery', 'BDSI');
        add('BioTelemetry', 'cardionet', 'BEAT');
        add('bebe stores', 'bebe-stores', 'BEBE');
        add('Beacon Roofing', 'beacon-roofing', 'BECN');
        add('Bel Fuse A', 'bel-fuse-inc-(a)', 'BELFA');
        add('Bel Fuse B', 'bel-fuse-inc-(b)', 'BELFB');
        add('Berkshire', 'berkshire-bancorp', 'BERK');
        add('BankFinancial', 'bankfinancial-corp', 'BFIN');
        add('BGC Partners', 'bgc-partners', 'BGCP');
        add('Big 5', 'big-5-sporting-go', 'BGFV');
        add('BG Medicine', 'bg-medicine', 'BGMD');
        add('Berkshire Hills Bancorp', 'berkshire-hills-b', 'BHLB');
        add('Biocept Inc', 'bioclinica', 'BIOC');
        add('Albireo Pharma', 'biodel-inc', 'ALBO');
        add('Green Brick Partners Inc', 'biofuel-energy', 'GRBK');
        add('BioScrip', 'bioscrip', 'BIOS');
        add('BJs Restaurants', 'bjs-restaurants', 'BJRI');
        add('Blueknight', 'blueknight-energy', 'BKEP');
        add('Bank Mutual', 'bank-mutual-corp', 'BKMU');
        add('Oak Ridge', 'oak-ridge-financial', 'BKOR');
        add('Bank of South Carolina', 'bank-of-south-car', 'BKSC');
        add('Builders FirstSource', 'builders-firstsou', 'BLDR');
        add('Bridgeline Digital', 'bridgeline-digita', 'BLIN');
        add('Blackbaud', 'blackbaud', 'BLKB');
        add('BSB Bancorp', 'bsb-bancorp', 'BLMT');
        add('BioLineRx', 'biolinerx-ltd', 'BLRX');
        add('Biolase', 'biolase-tech', 'BIOL');
        add('Bank of Marin', 'bank-of-marin-ban', 'BMRC');
        add('Biomarin Pharma', 'biomarin-pharmaceuticals', 'BMRN');
        add('Bryn Mawr Bank', 'bryn-mawr-bank-co', 'BMTC');
        add('Beneficial Mutual', 'beneficial-mutual', 'BNCL');
        add('Bonso Electronics Int', 'bonso-electronics', 'BNSO');
        add('Bob Evans', 'bob-evans-farms', 'BOBE');
        add('Bank of Commerce', 'bank-of-commerce', 'BOCH');
        add('BofI Holding', 'bofi-holding', 'BOFI');
        add('BOK Financial', 'bok-financial-corp', 'BOKF');
        add('The Bon-Ton', 'the-bon-ton-store', 'BONT');
        add('Dmc Global', 'dynamic-materials', 'BOOM');
        add('BOS', 'b.o.s.-better-onl', 'BOSC');
        add('Boston Private', 'boston-private-fi', 'BPFH');
        add('Modsys', 'bluephoenix-solut', 'MDSYF');
        add('Bridgford', 'bridgford-foods-c', 'BRID');
        add('Brookline Bancorp', 'brookline-bancorp', 'BRKL');
        add('Brooks Automation', 'brooks-automation', 'BRKS');
        add('Bassett', 'bassett-furniture', 'BSET');
        add('BroadSoft', 'broadsoft', 'BSFT');
        add('Biostar', 'biostar-pharmaceuticals', 'BSPM');
        add('BSQUARE', 'bsquare-corp', 'BSQR');
        add('Sierra Bancorp', 'sierra-bancorp', 'BSRR');
        add('BioSpecifics', 'biospecifics-tech', 'BSTC');
        add('Burcon Nutrascience Corp', 'burcon-nutrascience-corp?cid=15617', 'BUR');
        add('First Busey', 'first-busey-corp', 'BUSE');
        add('BroadVision', 'broadvision', 'BVSN');
        add('Broadwind', 'broadwind-energy', 'BWEN');
        add('Baldwin&Lyons A', 'baldwin---lyons-(a)', 'BWINA');
        add('Baldwin&Lyons B', 'baldwin---lyons-(b)', 'BWINB');
        add('Broadway Financial', 'broadway-financial', 'BYFC');
        add('China Automotive', 'china-automotive', 'CAAS');
        add('Camden', 'camden-national', 'CAC');
        add('Credit Acceptance', 'credit-acceptance', 'CACC');
        add('Cache', 'cache', 'CACH');
        add('China Construction Materials', 'china-advanced', 'CADC');
        add('The Cheesecake', 'the-cheesecake-factory', 'CAKE');
        add('Callidus', 'callidus-software', 'CALD');
        add('China Auto Logistics', 'china-auto-logist', 'CALI');
        add('magicJack VocalTec', 'magicjack-vocalte', 'CALL');
        add('Cal-Maine', 'cal-maine-foods', 'CALM');
        add('CalAmp', 'calamp-corp', 'CAMP');
        add('Camtek Ltd', 'camtek?cid=15640', 'CAMT');
        add('Carbonite', 'carbonite', 'CARB');
        add('Carolina Trust Bank', 'carolina-trust', 'CART');
        add('Carver', 'carver-bancorp', 'CARV');
        add('Meta Financial', 'meta-financial', 'CASH');
        add('CAS Medical', 'cas-medical-systems-inc', 'CASM');
        add('Cass', 'cass-information', 'CASS');
        add('Caseys', 'caseys-general', 'CASY');
        add('Cardtronics', 'cardtronics', 'CATM');
        add('Cathay', 'cathay-general', 'CATY');
        add('Cavium', 'cavium', 'CAVM');
        add('Net Element', 'net-element-inc', 'NETE');
        add('China Bak Battery', 'china-bak-battery', 'CBAK');
        add('Colony Bankcorp', 'colony-bankcorp', 'CBAN');
        add('Cleveland BioLabs', 'cleveland-biolabs', 'CBLI');
        add('CombiMatrix', 'combimatrix-corp', 'CBMX');
        add('China Biologic', 'china-biologic-products', 'CBPO');
        add('Cracker Barrel Old', 'cracker-barrelold-country', 'CBRL');
        add('Juniper Pharma', 'columbialaboratories', 'JNP');
        add('Commerce Bancshares', 'commerce-bancshar', 'CBSH');
        add('Capital City Bank', 'capital-city-bank', 'CCBG');
        add('China Ceramics Co', 'china-ceramics', 'CCCL');
        add('ChinaCaches', 'chinacache', 'CCIH');
        add('CNB Financial', 'cnb-financial-corp', 'CCNE');
        add('Cogent', 'cogent-communications', 'CCOI');
        add('Cross Country', 'cross-country', 'CCRN');
        add('Concurrent Computer', 'concurrent-comput', 'CCUR');
        add('Codexis', 'codexis', 'CDXS');
        add('Cadiz', 'cadiz', 'CDZI');
        add('CECO Environmental', 'ceco-environmenta', 'CECE');
        add('Career', 'career-education', 'CECO');
        add('Central Garden&Pet', 'central-garden---pet-co.', 'CENT');
        add('Central Garden&Pet A', 'central-garden-pet-a', 'CENTA');
        add('Cereplast Inc', 'cereplast', 'CERPQ');
        add('Cerus', 'cerus-corp', 'CERS');
        add('Central European Media', 'cent-euro-medi?cid=15692', 'CETV');
        add('CEVA', 'ceva', 'CEVA');
        add('Central Federal', 'central-federal', 'CFBK');
        add('C&F Financial', 'c-f-financial-corp', 'CFFI');
        add('Capitol Federal', 'capitol-federal-financial', 'CFFN');
        add('California First National', 'california-first', 'CFNB');
        add('Pingtan Marine', 'pingtan-marine', 'PME');
        add('Compugen Ltd', 'compugen?cid=15702', 'CGEN');
        add('Cognex', 'cognex-corp', 'CGNX');
        add('Comstock', 'comstock-homebuil', 'CHCI');
        add('City Holding', 'city-holding-comp', 'CHCO');
        add('Churchill Downs', 'churchill-downs', 'CHDN');
        add('The Chefs Warehouse', 'the-chefs-warehouse', 'CHEF');
        add('Chemical', 'chemical-financial', 'CHFC');
        add('Charter Financial', 'charter-financial', 'CHFN');
        add('Cherokee', 'cherokee-inc', 'CHKE');
        add('China Natural Resources', 'china-natural', 'CHNR');
        add('China Gerui Advanced Materials', 'china-gerui', 'CHOPF');
        add('Coherus BioSciences', 'charming-shoppes', 'CHRS');
        add('Charter Communications', 'charter-communications', 'CHTR');
        add('Cinedigm', 'cinedigm-digital', 'CIDM');
        add('Fanhua', 'cninsure-inc', 'FANH');
        add('Citizens', 'citizens-holding', 'CIZN');
        add('China Jo-Jo Drugstores', 'china-jo-jo-drugs', 'CJJD');
        add('Collectors Universe', 'collectors-univer', 'CLCT');
        add('Celldex', 'celldex-therapeutics', 'CLDX');
        add('Clearfield', 'clearfield', 'CLFD');
        add('Calumet', 'calumet-specialty', 'CLMT');
        add('Clean Energy', 'clean-energy-fuel', 'CLNE');
        add('Cleantech Solutions Int', 'cleantech', 'CLNT');
        add('ClearOne', 'clearone-communications', 'CLRO');
        add('Town Sportss', 'town-sports-international', 'CLUB');
        add('Clovis', 'clovis-oncology', 'CLVS');
        add('Euro Tech', 'euro-tech-holding', 'CLWT');
        add('Columbus McKinnon', 'columbus-mckinnon', 'CMCO');
        add('Cumulus', 'cumulus-media-inc', 'CMLS');
        add('Destination XL Group', 'destination-xl', 'DXLG');
        add('Comtech', 'comtech-tele', 'CMTL');
        add('Commercial National Financial', 'commercial-nation', 'CNAF');
        add('Century Bancorp', 'century-bancorp', 'CNBKA');
        add('Fortress Biotech', 'coronado-bioscien', 'FBIO');
        add('Chinanet Online', 'chinanet-online', 'CNET');
        add('China Information Tech', 'china-information', 'CNIT');
        add('CONMED', 'conmed-corp', 'CNMD');
        add('Consolidated Communications', 'consolidated-comm', 'CNSL');
        add('China Techfaith', 'china-techfaith', 'CNTF');
        add('Century Casinos', 'century-casinos', 'CNTY');
        add('CoBiz', 'cobiz-financial', 'COBZ');
        add('Viewtran Group Inc', 'cogo-group', 'VIEWF');
        add('Coherent', 'coherent', 'COHR');
        add('Cohu', 'cohu', 'COHU');
        add('Coca-Cola Bottling', 'coca-cola-bottlin', 'COKE');
        add('Columbia Banking', 'columbia-banking', 'COLB');
        add('Columbia Sportswear', 'columbia-sportswear', 'COLM');
        add('Conns', 'conns', 'CONN');
        add('Polarityte', 'majesco-entertainment', 'COOL');
        add('Core-Mark', 'core-mark-holding', 'CORE');
        add('Corcept', 'corcept-therapeutics', 'CORT');
        add('Cowen Group', 'cowen-group', 'COWN');
        add('Two Rivers Bancorp', 'two-rivers-bancorp', 'TRCB');
        add('Canterbury Park', 'canterbury-park', 'CPHC');
        add('Cumberland', 'cumberland-pharma', 'CPIX');
        add('Capella', 'capella-education', 'CPLA');
        add('Capital Product Partners', 'capital-product-partners', 'CPLP');
        add('Catalyst Pharmaceuticals', 'catalyst-pharmaceuticals', 'CPRX');
        add('Computer Programs&Systems', 'computer-programs', 'CPSI');
        add('China Precision Steel', 'china-precision', 'CPSL');
        add('Consumer Portfolio Services', 'consumer-portfolio', 'CPSS');
        add('CRA', 'cra-international', 'CRAI');
        add('Cray', 'cray-inc', 'CRAY');
        add('Dextera Surgical', 'cardica', 'DXTR');
        add('China Recycling Energy', 'china-recycling', 'CREG');
        add('Cresud SACIF', 'cresud-s.a.c.i.f.', 'CRESY');
        add('Curis', 'curis', 'CRIS');
        add('Crumbs', 'crumbs-bake-shop', 'CRMBQ');
        add('Cardiome Pharma Corp', 'cardiome-pharma-corp?cid=15813', 'CRME');
        add('Americas Car-Mart', 'americas-car-mart', 'CRMT');
        add('Ceragon Networks Ltd', 'ceragon?cid=15815', 'CRNT');
        add('Bay Bancorp Inc', 'carrollton-bancor', 'BYBK');
        add('CorVel', 'corvel-corp', 'CRVL');
        add('Crown Crafts', 'crown-crafts', 'CRWS');
        add('Carrizo Oil&Gas', 'carrizo-oil---gas', 'CRZO');
    }

    function add(name, url, shortName) {
            _stocks.push({
                name,
                url: urlBase + url,
                shortName
            });
    }

    ctor();
}